spring:
  security:
    oauth2:
      resourceserver:
        opaquetoken:
#          client-id: relive-client
#          client-secret: relive-client
          client-id: token-client
          client-secret: token
          introspection-uri: http://127.0.0.1:8090/oauth2/introspect
