server:
  port: 10011

spring:
  application:
    name: mall-order-service

#   datasource:
#     type: com.alibaba.druid.pool.DruidDataSource
#     driver-class-name: com.mysql.cj.jdbc.Driver
#     url: jdbc:mysql://node-200:3306/mall-cloud-ddd?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
#     username: gexingw
#     password: 12345678
